### ISSUE TITLE
末影龙血量无法修改

### ISSUE THREAD

**Issue by Hurry1027** [Tsubasa6848/FerociousEnderDragon#3]
服务端版本1.19.81 LL2.13.0
1、config.json 末影龙血量无法修改。修改后重启会重置为2000
2、末影龙无法被近战伤害？末影龙没有受伤音效。
3、卸载插件后kill强化末影龙，在其他维度死亡重生后会被冻结和鬼畜十几秒，在装载插件时是否正常没有测试。
4、建议默认配置文件为原版末影龙参数，或者在插件介绍中说明原版强度参数，便于腐竹判断末影龙加强程度。
（原版200血加强到2000有点离谱）

**Comment by KobeBryant114514** [comment]
> 2、末影龙无法被近战伤害？末影龙没有受伤音效。

配置文件有一项，栖息状态下末影龙无法受到伤害。



> 3、卸载插件后kill强化末影龙，在其他维度死亡重生后会被冻结和鬼畜十几秒，在装载插件时是否正常没有测试。

大概率mojang的bug，我到时候再具体试试

**Comment by KobeBryant114514** [comment]
> 3、卸载插件后kill强化末影龙，在其他维度死亡重生后会被冻结和鬼畜十几秒，在装载插件时是否正常没有测试。

无法复现？


> 1、config.json 末影龙血量无法修改。修改后重启会重置为2000

已修复
