### ISSUE TITLE
bds1.20.0-LL2.14.0下启动崩服

### ISSUE THREAD

**Issue by bbsupn** [Tsubasa6848/FerociousEnderDragon#4]
![image](https://github.com/Tsubasa6848/FerociousEnderDragon/assets/85688636/72354fb0-fc42-4018-85d8-f33c5a7cdbc4)
这是崩服输出

**Comment by yufengya0420** [comment]
BDS 1.12.0 你是什么远古版本 配 高版本LL

**Comment by bbsupn** [comment]
打错了，是1.20.0.01

**Comment by bbsupn** [comment]
[trace_2023-06-17_16-47-57.log](https://github.com/Tsubasa6848/FerociousEnderDragon/files/11778400/trace_2023-06-17_16-47-57.log)
这是完整堆栈报告

**Comment by bbsupn** [comment]
> BDS 1.12.0 你是什么远古版本 配 高版本LL

改过来了标题打错了

**Comment by whitebear2333** [comment]
我也是一模一样的问题

**Comment by KobeBryant114514** [comment]
> 我也是一模一样的问题



> > BDS 1.12.0 你是什么远古版本 配 高版本LL
> 
> 改过来了标题打错了



> BDS 1.12.0 你是什么远古版本 配 高版本LL

已修复，请从minebbs下载最新版本
