### ISSUE TITLE
关于平分机制的问题

### ISSUE THREAD

**Issue by lthuas** [Tsubasa6848/FerociousEnderDragon#6]
希望能在伤害最小的玩家和伤害最大的玩家的平分的金币能聚拢一点，伤害最大的玩家不要获益倍数太大，有点只能分一两百，有的能分一两千这种（希望差距不要这么大，可以把第一的半数金额来填补后面玩家的奖励，让玩家之间获得的金额差距能非常小）这个建议我可能没办法说清楚大概是什么样的，非常抱歉，大概是这个样owo

**Comment by KobeBryant114514** [comment]
你是希望平分还是什么？

**Comment by lthuas** [comment]
> 希望能在伤害最小的玩家和伤害最大的玩家的平分的金币能聚拢一点，伤害最大的玩家不要获益倍数太大，有点只能分一两百，有的能分一两千这种（希望差距不要这么大，可以把第一的半数金额来填补后面玩家的奖励，让玩家之间获得的金额差距能非常小）这个建议我可能没办法说清楚大概是什么样的，非常抱歉，大概是这个样owo



> 你是希望平分还是什么？

非常抱歉这段时间我一直登不上github没有及时回复您，目前这条建议我想撤回了，但是手机上不知道该怎么删除，可能需要麻烦您删下该帖
