### ISSUE TITLE
plugin make bds crash when i hit ender dragon

### ISSUE THREAD

**Issue by Futureganteng** [Tsubasa6848/FerociousEnderDragon#7]
I have an issue when i hit my ender dragon the bds crashed
im using bedrock 1.20.1
Network Protocol 589
Liteloader version: 2.14.1
how to reproduce?

config attached
[config.zip](https://github.com/Tsubasa6848/FerociousEnderDragon/files/12210698/config.zip)

tell me if there was a way to fix this crash.

**Comment by KobeBryant114514** [comment]
Please give me the crash log and dmp.

**Comment by Futureganteng** [comment]
where do i send the dmp?, do you have an email?

**Comment by KobeBryant114514** [comment]
> 

Package the file into a zip and send it as an attachment.
Need not to send Email, just attach files on github.
I need .log and .dmp to analyze the cause of the crash. These files will automatically generate in ./logs/crash when server crashed.

**Comment by Futureganteng** [comment]
sorry for late respond, i will send the file ASAP, because i was on vacation.

**Comment by Futureganteng** [comment]
sorry for late response, its fixed thank you
